"""Connecting an academy's payment gateways, from Manage → Integrations.

Admin-only, with one exception. Pasting a Razorpay key secret is an owner-level act
— it decides where the academy's money lands — so it sits alongside issuing partner
API keys at `RequireAdmin`, out of reach of reception and of the shared kiosk login.

The exception is `GET /payments/active`, which the counter tablet has to be able to
read to know which gateway to charge through. It returns the public half only.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Annotated

from fastapi import APIRouter, Query, status
from sqlalchemy import select

from app.auth.deps import RequireAdmin, RequireKiosk
from app.core import crypto
from app.core.errors import ConflictError, InvalidInputError, NotFoundError
from app.modules.payments import service
from app.modules.payments import verify as verify_module
from app.modules.payments.catalog import (
    BY_ID,
    CATALOG,
    PaymentProvider,
    ProviderSpec,
    format_problems,
)
from app.modules.payments.models import PaymentProviderConfig, surface_column
from app.modules.payments.schemas import (
    ActiveGatewayOut,
    IntegrationsOut,
    ProviderConfigOut,
    ProviderConfigUpsert,
    ProviderFieldOut,
    ProviderOut,
    ProviderSaveOut,
    RoutingUpdate,
    VerificationOut,
)
from app.tenancy.deps import Db

router = APIRouter(prefix="/payments", tags=["payments"])


def _spec(provider: PaymentProvider) -> ProviderSpec:
    spec = BY_ID.get(provider)
    if spec is None:  # pragma: no cover — the path param is the enum itself
        raise NotFoundError(f"Unknown payment provider {provider!r}.")
    return spec


def _fields_out(spec: ProviderSpec) -> list[ProviderFieldOut]:
    return [
        ProviderFieldOut(
            name=f.name,
            label=f.label,
            placeholder=f.placeholder,
            help=f.help,
            secret=f.secret,
            required=f.required,
            mode_prefixes=dict(f.mode_prefixes),
        )
        for f in spec.fields
    ]


async def _config(db: Db, provider: PaymentProvider) -> PaymentProviderConfig | None:
    result = await db.execute(
        select(PaymentProviderConfig).where(PaymentProviderConfig.provider == provider)
    )
    return result.scalar_one_or_none()


async def _out(db: Db, config: PaymentProviderConfig) -> ProviderConfigOut:
    """Serialise a row that was just written.

    The refresh is load-bearing, not defensive. `updated_at` is generated by SQL
    (`TimestampMixin.onupdate=func.now()`), so after a flush SQLAlchemy marks it
    expired — and reading an expired attribute emits a SELECT. Pydantic's validation
    is synchronous, so that SELECT lands outside the greenlet and raises
    MissingGreenlet rather than returning a value.

    Only the handlers that mutate need this. Read paths serialise loaded rows.
    """
    await db.refresh(config)
    return ProviderConfigOut.model_validate(config)


async def _require_config(db: Db, provider: PaymentProvider) -> PaymentProviderConfig:
    config = await _config(db, provider)
    if config is None:
        raise NotFoundError(f"{_spec(provider).label} is not connected.")
    return config


def _require_secrets_available() -> None:
    """Refuse to take a credential we cannot store safely.

    The alternative — falling back to plaintext when no key is configured — is the
    failure mode this whole module exists to prevent, and it would be invisible.
    A 409 that says why is better than a database full of readable payment secrets.
    """
    if not crypto.is_configured():
        raise ConflictError(
            "This deployment cannot store payment credentials: SECRETS_ENCRYPTION_KEY "
            "is not configured. Set it and restart the API before connecting a gateway."
        )


@router.get(
    "/providers",
    response_model=IntegrationsOut,
    summary="Payment gateways and how this academy has configured them",
    description=(
        "Everything the Integrations screen needs in one call: the gateways we "
        "support, the fields each one wants, and this academy's saved configuration "
        "where it exists.\n\n"
        "**No secret is ever in this response.** Saved secrets come back as "
        "`secret_hints` — the last four characters — which is enough to recognise a "
        "key and useless to anyone who intercepts it."
    ),
)
async def list_providers(db: Db, _: RequireAdmin) -> IntegrationsOut:
    rows = (await db.execute(select(PaymentProviderConfig))).scalars().all()
    by_provider = {row.provider: row for row in rows}

    return IntegrationsOut(
        secrets_available=crypto.is_configured(),
        providers=[
            ProviderOut(
                id=spec.id,
                label=spec.label,
                tagline=spec.tagline,
                credentials_url=spec.credentials_url,
                docs_url=spec.docs_url,
                supports_live_check=spec.supports_live_check,
                fields=_fields_out(spec),
                config=(
                    ProviderConfigOut.model_validate(by_provider[spec.id])
                    if spec.id in by_provider
                    else None
                ),
            )
            for spec in CATALOG
        ],
    )


@router.put(
    "/providers/{provider}",
    response_model=ProviderSaveOut,
    summary="Connect a gateway, or replace its credentials",
    description=(
        "Idempotent — the same call connects a new gateway and edits an existing "
        "one, because from the screen's point of view they are the same action.\n\n"
        "**Leave a secret field blank to keep the stored value.** The browser was "
        "never sent the real secret, so an edit that only changes the mode would "
        "otherwise wipe a working key.\n\n"
        "Credentials are checked for shape before saving (a test key saved as live "
        "is rejected with **400** and per-field messages) and then, unless "
        "`verify` is false, against the provider itself. A failed verification does "
        "**not** fail the save: an unreachable provider is not a wrong key."
    ),
)
async def upsert_provider(
    provider: PaymentProvider,
    payload: ProviderConfigUpsert,
    db: Db,
    principal: RequireAdmin,
) -> ProviderSaveOut:
    _require_secrets_available()
    spec = _spec(provider)

    config = await _config(db, provider)
    merged = service.merge_submitted(spec, config, payload.values)

    problems = format_problems(spec, payload.mode, merged)
    if problems:
        raise InvalidInputError(
            f"These {spec.label} credentials do not look right.",
            details={"problems": problems},
        )

    if config is None:
        config = PaymentProviderConfig(provider=provider)
        db.add(config)

    service.apply_credentials(
        config, spec, payload.mode, merged, actor_email=principal.email
    )
    await db.flush()

    verification: VerificationOut | None = None
    if payload.verify:
        verification = await _run_verification(config, spec)
        await db.flush()

    return ProviderSaveOut(config=await _out(db, config), verification=verification)


@router.post(
    "/providers/{provider}/verify",
    response_model=VerificationOut,
    summary="Re-check stored credentials against the provider",
    description=(
        "For the case a key worked when it was pasted and has since been revoked or "
        "rotated at the provider — which otherwise stays invisible until a customer "
        "cannot pay.\n\n"
        "`checked_live: false` means we could not actually ask: either the provider "
        "has no read-only endpoint to test against (PhonePe and PayU sign each "
        "request, so the only way to exercise a credential is to start a payment) or "
        "the call did not complete. Not the same as a wrong credential."
    ),
)
async def verify_provider(
    provider: PaymentProvider, db: Db, _: RequireAdmin
) -> VerificationOut:
    config = await _require_config(db, provider)
    result = await _run_verification(config, _spec(provider))
    await db.flush()
    return result


async def _run_verification(
    config: PaymentProviderConfig, spec: ProviderSpec
) -> VerificationOut:
    """Call the provider and record the answer on the row.

    Only a live check writes `last_verified_at`. A timeout or an unsupported
    provider leaves the previous result standing rather than overwriting a genuine
    green tick with "we could not tell", which would train people to ignore it.
    """
    result = await verify_module.verify(
        spec.id,
        config.mode,
        {str(k): str(v) for k, v in config.public_config.items()},
        service.read_secrets(config),
    )

    if result.checked_live:
        config.last_verified_at = datetime.now(UTC) if result.ok else None
        config.last_verification_error = None if result.ok else result.message

    return VerificationOut(
        ok=result.ok, message=result.message, checked_live=result.checked_live
    )


@router.patch(
    "/providers/{provider}/routing",
    response_model=ProviderConfigOut,
    summary="Choose which surfaces this gateway collects for",
    description=(
        "Turning a surface on takes it away from whichever gateway currently holds "
        "it — only one gateway can collect for the dashboard, and one for the POS. "
        "That is a unique index in Postgres, not a promise this handler makes.\n\n"
        "The two surfaces are independent on purpose: an academy can move online "
        "payments to a new gateway while the counter tablet stays on the old one."
    ),
)
async def update_routing(
    provider: PaymentProvider, payload: RoutingUpdate, db: Db, _: RequireAdmin
) -> ProviderConfigOut:
    config = await _require_config(db, provider)
    spec = _spec(provider)

    if (payload.collect_on_web or payload.collect_on_pos) and not config.is_configured:
        raise ConflictError(
            f"{spec.label} has no saved credentials, so it cannot collect payments. "
            "Add its API keys first."
        )

    others = (
        (
            await db.execute(
                select(PaymentProviderConfig).where(
                    PaymentProviderConfig.provider != provider
                )
            )
        )
        .scalars()
        .all()
    )

    # Two flushes, in this order, deliberately. The unique indexes are checked per
    # statement, so writing "Razorpay collects on web" while Cashfree still holds
    # that flag is a violation — even though the end state is fine. Clearing first
    # and claiming second is what makes a straight swap possible at all; SQLAlchemy
    # gives no ordering guarantee between two dirty rows in one flush.
    for field in ("collect_on_web", "collect_on_pos"):
        wanted = getattr(payload, field)
        if wanted:
            for other in others:
                setattr(other, field, False)
    await db.flush()

    for field in ("collect_on_web", "collect_on_pos"):
        wanted = getattr(payload, field)
        if wanted is not None:
            setattr(config, field, wanted)
    await db.flush()

    return await _out(db, config)


@router.delete(
    "/providers/{provider}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Disconnect a gateway",
    description=(
        "Deletes the stored credentials outright. This is also the only way to "
        "remove a secret — a blank field on save means 'keep the stored value', so "
        "there is no half-configured state to get stuck in.\n\n"
        "If this gateway was collecting for a surface, that surface is left with no "
        "gateway and stops taking online payments until another is chosen."
    ),
)
async def delete_provider(provider: PaymentProvider, db: Db, _: RequireAdmin) -> None:
    config = await _require_config(db, provider)
    await db.delete(config)
    await db.flush()


@router.get(
    "/active",
    response_model=ActiveGatewayOut | None,
    summary="Which gateway collects on this surface",
    description=(
        "What a checkout calls before starting a payment. Returns `null` when no "
        "gateway is configured for the surface, which means collect by cash or UPI "
        "at the counter as before — not an error.\n\n"
        "Readable by the counter tablet, unlike the rest of this module: the POS has "
        "to know which gateway to charge through. Only the public half is returned "
        "— the key id a client SDK needs. Signing an order stays server-side."
    ),
)
async def active_gateway(
    db: Db,
    _: RequireKiosk,
    surface: Annotated[str, Query(pattern="^(web|pos)$")] = "web",
) -> ActiveGatewayOut | None:
    column = surface_column(surface)
    config = (
        await db.execute(select(PaymentProviderConfig).where(column.is_(True)))
    ).scalar_one_or_none()

    if config is None:
        return None
    return ActiveGatewayOut(
        provider=config.provider,
        label=_spec(config.provider).label,
        mode=config.mode,
        public_config=dict(config.public_config),
    )
