"""academy: coaches, programs, batches, students, sessions

Revision ID: 08086a434746
Revises: 0bebc07e8e64
Create Date: 2026-08-02 01:33:10.523613
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic_rls import protect, unprotect

revision: str = '08086a434746'
down_revision: Union[str, None] = '0bebc07e8e64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

TABLES = (
    "coach",
    "coach_sport",
    "program",
    "batch",
    "student",
    "student_enrollment",
    "coaching_session",
    "attendance",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach',
    sa.Column('coach_no', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('avatar_initials', sa.String(length=4), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('specialization', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('full-time', 'part-time', 'guest', 'visiting', name='coach_type', native_enum=False, length=32), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('morning_available', sa.Boolean(), nullable=False),
    sa.Column('evening_available', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'on-leave', name='coach_status', native_enum=False, length=32), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_coach_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coach'))
    )
    op.create_index(op.f('ix_coach_tenant_id'), 'coach', ['tenant_id'], unique=False)
    op.create_index('ix_coach_tenant_status', 'coach', ['tenant_id', 'status'], unique=False)
    op.create_index('uq_coach_tenant_email', 'coach', ['tenant_id', sa.literal_column('lower(email)')], unique=True, postgresql_where=sa.text('email IS NOT NULL'))
    op.create_index('uq_coach_tenant_number', 'coach', ['tenant_id', 'coach_no'], unique=True)
    op.create_table('coach_sport',
    sa.Column('coach_id', sa.UUID(), nullable=False),
    sa.Column('sport_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coach.id'], name=op.f('fk_coach_sport_coach_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sport_id'], ['sport.id'], name=op.f('fk_coach_sport_sport_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_coach_sport_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coach_sport'))
    )
    op.create_index(op.f('ix_coach_sport_tenant_id'), 'coach_sport', ['tenant_id'], unique=False)
    op.create_index('uq_coach_sport_tenant_pair', 'coach_sport', ['tenant_id', 'coach_id', 'sport_id'], unique=True)
    op.create_table('program',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('sport_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('age_group', sa.String(length=50), nullable=True),
    sa.Column('duration_label', sa.String(length=50), nullable=True),
    sa.Column('max_students', sa.Integer(), nullable=False),
    sa.Column('session_freq', sa.String(length=50), nullable=True),
    sa.Column('session_duration', sa.String(length=50), nullable=True),
    sa.Column('coach_id', sa.UUID(), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('fee_1m', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fee_3m', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fee_6m', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fee_12m', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('color', sa.String(length=9), nullable=True),
    sa.Column('bg_color', sa.String(length=9), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coach.id'], name=op.f('fk_program_coach_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sport_id'], ['sport.id'], name=op.f('fk_program_sport_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_program_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_program'))
    )
    op.create_index(op.f('ix_program_tenant_id'), 'program', ['tenant_id'], unique=False)
    op.create_index('uq_program_tenant_name', 'program', ['tenant_id', 'name'], unique=True)
    op.create_table('batch',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('sport_id', sa.UUID(), nullable=True),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('coach_id', sa.UUID(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('schedule', sa.String(length=100), nullable=True),
    sa.Column('time_label', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'upcoming', 'completed', name='batch_status', native_enum=False, length=32), nullable=False),
    sa.Column('color', sa.String(length=9), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacity > 0', name=op.f('ck_batch_capacity_positive')),
    sa.ForeignKeyConstraint(['coach_id'], ['coach.id'], name=op.f('fk_batch_coach_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], name=op.f('fk_batch_program_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sport_id'], ['sport.id'], name=op.f('fk_batch_sport_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_batch_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batch'))
    )
    op.create_index('ix_batch_tenant_coach', 'batch', ['tenant_id', 'coach_id'], unique=False)
    op.create_index(op.f('ix_batch_tenant_id'), 'batch', ['tenant_id'], unique=False)
    op.create_index('ix_batch_tenant_program', 'batch', ['tenant_id', 'program_id'], unique=False)
    op.create_index('uq_batch_tenant_name', 'batch', ['tenant_id', 'name'], unique=True)
    op.create_table('student',
    sa.Column('student_no', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('parent_name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('avatar_initials', sa.String(length=4), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('blood_group', sa.String(length=8), nullable=True),
    sa.Column('status', sa.Enum('active', 'paused', 'completed', 'inactive', name='student_status', native_enum=False, length=32), nullable=False),
    sa.Column('performance_rating', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('achievements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_student_customer_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_student_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student'))
    )
    op.create_index(op.f('ix_student_tenant_id'), 'student', ['tenant_id'], unique=False)
    op.create_index('ix_student_tenant_name', 'student', ['tenant_id', 'name'], unique=False)
    op.create_index('ix_student_tenant_status', 'student', ['tenant_id', 'status'], unique=False)
    op.create_index('uq_student_tenant_number', 'student', ['tenant_id', 'student_no'], unique=True)
    op.create_table('coaching_session',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('coach_id', sa.UUID(), nullable=True),
    sa.Column('sport_id', sa.UUID(), nullable=True),
    sa.Column('batch_name', sa.String(length=150), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'ongoing', 'completed', 'cancelled', name='coaching_session_status', native_enum=False, length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ends_at > starts_at', name=op.f('ck_coaching_session_ends_after_starts')),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], name=op.f('fk_coaching_session_batch_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coach_id'], ['coach.id'], name=op.f('fk_coaching_session_coach_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sport_id'], ['sport.id'], name=op.f('fk_coaching_session_sport_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_coaching_session_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coaching_session'))
    )
    op.create_index('ix_coaching_session_tenant_batch', 'coaching_session', ['tenant_id', 'batch_id', 'starts_at'], unique=False)
    op.create_index('ix_coaching_session_tenant_coach', 'coaching_session', ['tenant_id', 'coach_id'], unique=False)
    op.create_index(op.f('ix_coaching_session_tenant_id'), 'coaching_session', ['tenant_id'], unique=False)
    op.create_index('ix_coaching_session_tenant_starts', 'coaching_session', ['tenant_id', 'starts_at'], unique=False)
    op.create_table('student_enrollment',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('coach_id', sa.UUID(), nullable=True),
    sa.Column('duration', sa.String(length=8), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('renewal_date', sa.Date(), nullable=False),
    sa.Column('total_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'cancelled', name='enrollment_status', native_enum=False, length=32), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], name=op.f('fk_student_enrollment_batch_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['coach_id'], ['coach.id'], name=op.f('fk_student_enrollment_coach_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], name=op.f('fk_student_enrollment_program_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_student_enrollment_student_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_student_enrollment_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_enrollment'))
    )
    op.create_index('ix_student_enrollment_tenant_batch', 'student_enrollment', ['tenant_id', 'batch_id'], unique=False)
    op.create_index(op.f('ix_student_enrollment_tenant_id'), 'student_enrollment', ['tenant_id'], unique=False)
    op.create_index('ix_student_enrollment_tenant_status', 'student_enrollment', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_student_enrollment_tenant_student', 'student_enrollment', ['tenant_id', 'student_id'], unique=False)
    op.create_index('uq_student_enrollment_active', 'student_enrollment', ['tenant_id', 'student_id', 'batch_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('attendance',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('present', 'absent', 'late', 'not-started', name='attendance_status', native_enum=False, length=32), nullable=False),
    sa.Column('marked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('marked_by_user_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['coaching_session.id'], name=op.f('fk_attendance_session_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_attendance_student_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_attendance_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance'))
    )
    op.create_index(op.f('ix_attendance_tenant_id'), 'attendance', ['tenant_id'], unique=False)
    op.create_index('ix_attendance_tenant_student', 'attendance', ['tenant_id', 'student_id'], unique=False)
    op.create_index('uq_attendance_tenant_session_student', 'attendance', ['tenant_id', 'session_id', 'student_id'], unique=True)
    op.add_column('invoice', sa.Column('student_enrollment_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_invoice_student_enrollment_id'), 'invoice', 'student_enrollment', ['student_enrollment_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('tenant_settings', 'invoice_prefix',
               existing_type=sa.VARCHAR(length=8),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###

    # Widen the invoice source check to admit academy fees. Alembic's autogenerate
    # does not compare CHECK constraint expressions, so this is written by hand —
    # without it, every enrolment invoice violates the Phase 3 constraint.
    op.drop_constraint(op.f("ck_invoice_single_source"), "invoice", type_="check")
    op.create_check_constraint(
        "single_source",
        "invoice",
        "num_nonnulls(booking_id, member_subscription_id, student_enrollment_id) <= 1",
    )

    protect(TABLES)


def downgrade() -> None:
    unprotect(TABLES)

    op.drop_constraint(op.f("ck_invoice_single_source"), "invoice", type_="check")
    op.create_check_constraint(
        "single_source",
        "invoice",
        "num_nonnulls(booking_id, member_subscription_id) <= 1",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenant_settings', 'invoice_prefix',
               existing_type=sa.VARCHAR(length=8),
               server_default=sa.text("'XC'::character varying"),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_invoice_student_enrollment_id'), 'invoice', type_='foreignkey')
    op.drop_column('invoice', 'student_enrollment_id')
    op.drop_index('uq_attendance_tenant_session_student', table_name='attendance')
    op.drop_index('ix_attendance_tenant_student', table_name='attendance')
    op.drop_index(op.f('ix_attendance_tenant_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index('uq_student_enrollment_active', table_name='student_enrollment', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('ix_student_enrollment_tenant_student', table_name='student_enrollment')
    op.drop_index('ix_student_enrollment_tenant_status', table_name='student_enrollment')
    op.drop_index(op.f('ix_student_enrollment_tenant_id'), table_name='student_enrollment')
    op.drop_index('ix_student_enrollment_tenant_batch', table_name='student_enrollment')
    op.drop_table('student_enrollment')
    op.drop_index('ix_coaching_session_tenant_starts', table_name='coaching_session')
    op.drop_index(op.f('ix_coaching_session_tenant_id'), table_name='coaching_session')
    op.drop_index('ix_coaching_session_tenant_coach', table_name='coaching_session')
    op.drop_index('ix_coaching_session_tenant_batch', table_name='coaching_session')
    op.drop_table('coaching_session')
    op.drop_index('uq_student_tenant_number', table_name='student')
    op.drop_index('ix_student_tenant_status', table_name='student')
    op.drop_index('ix_student_tenant_name', table_name='student')
    op.drop_index(op.f('ix_student_tenant_id'), table_name='student')
    op.drop_table('student')
    op.drop_index('uq_batch_tenant_name', table_name='batch')
    op.drop_index('ix_batch_tenant_program', table_name='batch')
    op.drop_index(op.f('ix_batch_tenant_id'), table_name='batch')
    op.drop_index('ix_batch_tenant_coach', table_name='batch')
    op.drop_table('batch')
    op.drop_index('uq_program_tenant_name', table_name='program')
    op.drop_index(op.f('ix_program_tenant_id'), table_name='program')
    op.drop_table('program')
    op.drop_index('uq_coach_sport_tenant_pair', table_name='coach_sport')
    op.drop_index(op.f('ix_coach_sport_tenant_id'), table_name='coach_sport')
    op.drop_table('coach_sport')
    op.drop_index('uq_coach_tenant_number', table_name='coach')
    op.drop_index('uq_coach_tenant_email', table_name='coach', postgresql_where=sa.text('email IS NOT NULL'))
    op.drop_index('ix_coach_tenant_status', table_name='coach')
    op.drop_index(op.f('ix_coach_tenant_id'), table_name='coach')
    op.drop_table('coach')
    # ### end Alembic commands ###
