"""foundation: tenancy, auth, audit

Creates the five foundation tables and — the part autogenerate cannot know about —
the row-level security policies and role grants that make tenant isolation real.

Revision ID: 0a3362c950d9
Revises:
Create Date: 2026-08-01 20:18:54.261041
"""

import os
import re
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0a3362c950d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Tables owned by a tenant. Every one gets an RLS policy below.
#
# `tenant` and `platform_admin` are deliberately absent: they have no tenant_id.
# `tenant` must stay readable with nothing bound, because reading it is how a
# hostname becomes a tenant in the first place.
#
# Frozen as a literal rather than derived from Base.metadata: a migration describes
# the schema at one point in history, and importing live models would make this file
# silently change meaning as later phases add tables.
TENANT_SCOPED_TABLES = ("app_user", "audit_log", "tenant_settings")

POLICY_NAME = "tenant_isolation"

# Kept byte-identical to app/db/rls.py::TENANT_PREDICATE.
#   current_setting(_, true) -> NULL rather than an error when never set
#   nullif(_, '')            -> we clear by setting '', and ''::uuid would raise
#   tenant_id = NULL         -> never true, so an unbound session sees zero rows
TENANT_PREDICATE = "tenant_id = nullif(current_setting('app.current_tenant', true), '')::uuid"


def _app_role() -> str:
    """The role the API connects as. Interpolated into DDL, so it is validated."""
    role = os.environ.get("DB_APP_USER", "gamexo_app")
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", role):
        raise ValueError(f"DB_APP_USER is not a plain SQL identifier: {role!r}")
    return role


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_admin',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_admin'))
    )
    op.create_index(op.f('ix_platform_admin_email'), 'platform_admin', ['email'], unique=True)
    op.create_table('tenant',
    sa.Column('slug', sa.String(length=63), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('active', 'trial', 'suspended', name='tenant_status', native_enum=False, length=32), nullable=False),
    sa.Column('plan_tier', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant'))
    )
    op.create_index(op.f('ix_tenant_slug'), 'tenant', ['slug'], unique=True)
    op.create_table('app_user',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('admin', 'manager', 'reception', name='user_role', native_enum=False, length=32), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('avatar_initials', sa.String(length=4), nullable=True),
    sa.Column('shift', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('active', 'on-leave', 'inactive', name='user_status', native_enum=False, length=32), nullable=False),
    sa.Column('joined_on', sa.Date(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_app_user_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user'))
    )
    op.create_index(op.f('ix_app_user_tenant_id'), 'app_user', ['tenant_id'], unique=False)
    op.create_index('uq_app_user_tenant_email', 'app_user', ['tenant_id', sa.literal_column('lower(email)')], unique=True)
    op.create_table('audit_log',
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_kind', sa.Enum('user', 'platform_admin', 'system', name='audit_actor_kind', native_enum=False, length=32), nullable=False),
    sa.Column('actor_label', sa.String(length=320), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('tenant_source', sa.String(length=20), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_audit_log_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_log_tenant_actor', 'audit_log', ['tenant_id', 'actor_id'], unique=False)
    op.create_index('ix_audit_log_tenant_created', 'audit_log', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_audit_log_tenant_entity', 'audit_log', ['tenant_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_tenant_id'), 'audit_log', ['tenant_id'], unique=False)
    op.create_table('tenant_settings',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('gst_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('brand_primary', sa.String(length=9), nullable=False),
    sa.Column('brand_accent', sa.String(length=9), nullable=False),
    sa.Column('brand_background', sa.String(length=9), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('operating_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('booking_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tax_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('security_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notification_sender_name', sa.String(length=120), nullable=True),
    sa.Column('notification_sender_email', sa.String(length=320), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(business_name) > 0', name=op.f('ck_tenant_settings_business_name_not_blank')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_tenant_settings_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_settings'))
    )
    op.create_index(op.f('ix_tenant_settings_tenant_id'), 'tenant_settings', ['tenant_id'], unique=True)
    # ### end Alembic commands ###

    _apply_grants()
    _apply_rls()


def _apply_grants() -> None:
    """Give the API role exactly the rights it needs, and no more.

    docker/initdb/01-roles.sh already sets ALTER DEFAULT PRIVILEGES so tables created
    by the migrator are granted automatically. These statements repeat that
    explicitly so the migration is self-sufficient against a managed Postgres
    (Neon, RDS) that was provisioned without that bootstrap script — where the
    alternative is an API that authenticates fine and then 500s on every query.
    """
    app_role = _app_role()

    op.execute(f"GRANT USAGE ON SCHEMA public TO {app_role}")
    for table in ("tenant", "platform_admin", *TENANT_SCOPED_TABLES):
        op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE {table} TO {app_role}")

    # Append-only, enforced by the database rather than by convention.
    #
    # The value of an audit log is that it cannot be rewritten. If the application
    # role holds UPDATE and DELETE, then a bug, a compromised token or an injected
    # statement can erase the record of itself — and the log becomes evidence of
    # nothing. Purging for retention remains possible, but only as the migrator
    # role: a deliberate, reviewed act rather than something the API can do.
    op.execute(f"REVOKE UPDATE, DELETE ON TABLE audit_log FROM {app_role}")


def _apply_rls() -> None:
    """The database-level half of tenant isolation.

    This is the layer that holds when application code is wrong: a query that
    forgets its tenant filter returns nothing rather than everything.
    """
    for table in TENANT_SCOPED_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")

        # FORCE is not redundant. ENABLE alone leaves the table's OWNER exempt from
        # its own policies, and the owner is this migration role. Without FORCE,
        # anything connecting as the migrator — a seed script, a psql session opened
        # during an incident — reads every tenant's rows with no sign a policy exists.
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")

        # USING governs what SELECT/UPDATE/DELETE can see.
        # WITH CHECK governs what INSERT/UPDATE may write. Omitting WITH CHECK is the
        # classic half-implemented RLS: reads are isolated, but a tenant can still
        # INSERT a row stamped with another tenant's id, or UPDATE one of its own
        # rows to hand it to someone else.
        op.execute(
            f"CREATE POLICY {POLICY_NAME} ON {table} "
            f"USING ({TENANT_PREDICATE}) WITH CHECK ({TENANT_PREDICATE})"
        )


def downgrade() -> None:
    for table in TENANT_SCOPED_TABLES:
        op.execute(f"DROP POLICY IF EXISTS {POLICY_NAME} ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_settings_tenant_id'), table_name='tenant_settings')
    op.drop_table('tenant_settings')
    op.drop_index(op.f('ix_audit_log_tenant_id'), table_name='audit_log')
    op.drop_index('ix_audit_log_tenant_entity', table_name='audit_log')
    op.drop_index('ix_audit_log_tenant_created', table_name='audit_log')
    op.drop_index('ix_audit_log_tenant_actor', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('uq_app_user_tenant_email', table_name='app_user')
    op.drop_index(op.f('ix_app_user_tenant_id'), table_name='app_user')
    op.drop_table('app_user')
    op.drop_index(op.f('ix_tenant_slug'), table_name='tenant')
    op.drop_table('tenant')
    op.drop_index(op.f('ix_platform_admin_email'), table_name='platform_admin')
    op.drop_table('platform_admin')
    # ### end Alembic commands ###
