"""finance: numbering, invoices, payments, memberships

Revision ID: 0bebc07e8e64
Revises: ed815e231c5c
Create Date: 2026-08-01 21:17:15.365539
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic_rls import protect, unprotect

revision: str = '0bebc07e8e64'
down_revision: Union[str, None] = 'ed815e231c5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

TABLES = (
    "document_counter",
    "membership_plan",
    "member_subscription",
    "invoice",
    "payment",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_counter',
    sa.Column('kind', sa.Enum('invoice', 'member', 'coach', 'student', name='document_counter_kind', native_enum=False, length=32), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('last_value', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_document_counter_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_counter'))
    )
    op.create_index(op.f('ix_document_counter_tenant_id'), 'document_counter', ['tenant_id'], unique=False)
    op.create_index('uq_document_counter_tenant_kind_period', 'document_counter', ['tenant_id', 'kind', 'period'], unique=True)
    op.create_table('membership_plan',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=9), nullable=True),
    sa.Column('bg_color', sa.String(length=9), nullable=True),
    sa.Column('price_1m', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_3m', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_6m', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_12m', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('joining_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_pct', sa.Integer(), nullable=False),
    sa.Column('max_visits', sa.Integer(), nullable=True),
    sa.Column('benefits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_membership_plan_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_membership_plan'))
    )
    op.create_index(op.f('ix_membership_plan_tenant_id'), 'membership_plan', ['tenant_id'], unique=False)
    op.create_index('uq_membership_plan_tenant_name', 'membership_plan', ['tenant_id', 'name'], unique=True)
    op.create_table('member_subscription',
    sa.Column('member_no', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('plan_name', sa.String(length=150), nullable=False),
    sa.Column('plan_color', sa.String(length=9), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('duration', sa.Enum('1m', '3m', '6m', '12m', name='subscription_duration', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'paused', 'cancelled', name='subscription_status', native_enum=False, length=32), nullable=False),
    sa.Column('visits_used', sa.Integer(), nullable=False),
    sa.Column('total_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('referral_code', sa.String(length=64), nullable=True),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('expiry_date >= start_date', name=op.f('ck_member_subscription_expiry_after_start')),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_member_subscription_customer_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plan_id'], ['membership_plan.id'], name=op.f('fk_member_subscription_plan_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_member_subscription_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_member_subscription'))
    )
    op.create_index('ix_member_subscription_tenant_customer', 'member_subscription', ['tenant_id', 'customer_id'], unique=False)
    op.create_index('ix_member_subscription_tenant_expiry', 'member_subscription', ['tenant_id', 'expiry_date'], unique=False)
    op.create_index(op.f('ix_member_subscription_tenant_id'), 'member_subscription', ['tenant_id'], unique=False)
    op.create_index('ix_member_subscription_tenant_status', 'member_subscription', ['tenant_id', 'status'], unique=False)
    op.create_index('uq_member_subscription_tenant_number', 'member_subscription', ['tenant_id', 'member_no'], unique=True)
    op.create_table('invoice',
    sa.Column('invoice_no', sa.String(length=32), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('member_subscription_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('gst_number', sa.String(length=20), nullable=True),
    sa.Column('issue_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gst', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending', 'paid', 'overdue', 'cancelled', name='invoice_status', native_enum=False, length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('num_nonnulls(booking_id, member_subscription_id) <= 1', name=op.f('ck_invoice_single_source')),
    sa.CheckConstraint('total >= 0 AND amount_paid >= 0', name=op.f('ck_invoice_amounts_non_negative')),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], name=op.f('fk_invoice_booking_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_invoice_customer_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['member_subscription_id'], ['member_subscription.id'], name=op.f('fk_invoice_member_subscription_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_invoice_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice'))
    )
    op.create_index('ix_invoice_tenant_customer', 'invoice', ['tenant_id', 'customer_id'], unique=False)
    op.create_index(op.f('ix_invoice_tenant_id'), 'invoice', ['tenant_id'], unique=False)
    op.create_index('ix_invoice_tenant_issue_date', 'invoice', ['tenant_id', 'issue_date'], unique=False)
    op.create_index('ix_invoice_tenant_status', 'invoice', ['tenant_id', 'status'], unique=False)
    op.create_index('uq_invoice_tenant_number', 'invoice', ['tenant_id', 'invoice_no'], unique=True)
    op.create_table('payment',
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.Enum('cash', 'upi', 'card', 'bank', 'cheque', name='payment_method', native_enum=False, length=32), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('state', sa.Enum('captured', 'pending', 'failed', 'refunded', name='payment_state', native_enum=False, length=32), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('received_by_user_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_payment_amount_positive')),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], name=op.f('fk_payment_booking_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_payment_customer_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], name=op.f('fk_payment_invoice_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_payment_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment'))
    )
    op.create_index('ix_payment_tenant_booking', 'payment', ['tenant_id', 'booking_id'], unique=False)
    op.create_index(op.f('ix_payment_tenant_id'), 'payment', ['tenant_id'], unique=False)
    op.create_index('ix_payment_tenant_invoice', 'payment', ['tenant_id', 'invoice_id'], unique=False)
    op.create_index('ix_payment_tenant_method', 'payment', ['tenant_id', 'method'], unique=False)
    op.create_index('ix_payment_tenant_received', 'payment', ['tenant_id', 'received_at'], unique=False)
    op.add_column(
        'tenant_settings',
        # server_default backfills existing academies; the ORM default takes over for
        # new rows, so the column is NOT NULL from the start without a three-step
        # add-nullable / backfill / alter dance.
        sa.Column('invoice_prefix', sa.String(length=8), nullable=False, server_default='XC'),
    )
    # ### end Alembic commands ###

    protect(TABLES)


def downgrade() -> None:
    unprotect(TABLES)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_settings', 'invoice_prefix')
    op.drop_index('ix_payment_tenant_received', table_name='payment')
    op.drop_index('ix_payment_tenant_method', table_name='payment')
    op.drop_index('ix_payment_tenant_invoice', table_name='payment')
    op.drop_index(op.f('ix_payment_tenant_id'), table_name='payment')
    op.drop_index('ix_payment_tenant_booking', table_name='payment')
    op.drop_table('payment')
    op.drop_index('uq_invoice_tenant_number', table_name='invoice')
    op.drop_index('ix_invoice_tenant_status', table_name='invoice')
    op.drop_index('ix_invoice_tenant_issue_date', table_name='invoice')
    op.drop_index(op.f('ix_invoice_tenant_id'), table_name='invoice')
    op.drop_index('ix_invoice_tenant_customer', table_name='invoice')
    op.drop_table('invoice')
    op.drop_index('uq_member_subscription_tenant_number', table_name='member_subscription')
    op.drop_index('ix_member_subscription_tenant_status', table_name='member_subscription')
    op.drop_index(op.f('ix_member_subscription_tenant_id'), table_name='member_subscription')
    op.drop_index('ix_member_subscription_tenant_expiry', table_name='member_subscription')
    op.drop_index('ix_member_subscription_tenant_customer', table_name='member_subscription')
    op.drop_table('member_subscription')
    op.drop_index('uq_membership_plan_tenant_name', table_name='membership_plan')
    op.drop_index(op.f('ix_membership_plan_tenant_id'), table_name='membership_plan')
    op.drop_table('membership_plan')
    op.drop_index('uq_document_counter_tenant_kind_period', table_name='document_counter')
    op.drop_index(op.f('ix_document_counter_tenant_id'), table_name='document_counter')
    op.drop_table('document_counter')
    # ### end Alembic commands ###
