"""advertising: spots and contracts

Revision ID: 4cd4baa51635
Revises: 08086a434746
Create Date: 2026-08-02 01:45:03.639308
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic_rls import protect, unprotect

revision: str = '4cd4baa51635'
down_revision: Union[str, None] = '08086a434746'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

TABLES = ("ad_spot", "ad_contract")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_spot',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('zone', sa.String(length=100), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('dimensions', sa.String(length=64), nullable=True),
    sa.Column('type', sa.Enum('indoor', 'outdoor', name='ad_spot_type', native_enum=False, length=32), nullable=False),
    sa.Column('display_type', sa.String(length=64), nullable=True),
    sa.Column('visibility_rating', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('price_monthly', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_quarterly', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_yearly', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_sellable', sa.Boolean(), nullable=False),
    sa.Column('blocked_status', sa.Enum('maintenance', 'blocked', name='ad_spot_blocked_status', native_enum=False, length=32), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('visibility_rating >= 0 AND visibility_rating <= 10', name=op.f('ck_ad_spot_visibility_in_range')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_ad_spot_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ad_spot'))
    )
    op.create_index(op.f('ix_ad_spot_tenant_id'), 'ad_spot', ['tenant_id'], unique=False)
    op.create_index('ix_ad_spot_tenant_zone', 'ad_spot', ['tenant_id', 'zone'], unique=False)
    op.create_index('uq_ad_spot_tenant_code', 'ad_spot', ['tenant_id', 'code'], unique=True)
    op.create_table('ad_contract',
    sa.Column('spot_id', sa.UUID(), nullable=False),
    sa.Column('spot_name', sa.String(length=150), nullable=False),
    sa.Column('zone', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=150), nullable=True),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('gst', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('period', postgresql.DATERANGE(), sa.Computed("daterange(start_date, end_date, '[]')", persisted=True), nullable=False),
    sa.Column('duration_label', sa.String(length=32), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deposit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('installation_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('printing_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('draft', 'quotation', 'confirmed', 'active', 'expiring', 'expired', 'renewed', 'cancelled', name='ad_contract_status', native_enum=False, length=32), nullable=False),
    sa.Column('payment_status', sa.Enum('paid', 'pending', 'partial', name='ad_contract_payment_status', native_enum=False, length=32), nullable=False),
    sa.Column('timeline', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    postgresql.ExcludeConstraint((sa.column('tenant_id'), '='), (sa.column('spot_id'), '='), (sa.column('period'), '&&'), where=sa.text("status IN ('confirmed', 'active', 'renewed')"), using='gist', name='ad_contract_no_overlap'),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_ad_contract_end_after_start')),
    sa.CheckConstraint('paid >= 0 AND total >= 0', name=op.f('ck_ad_contract_amounts_non_negative')),
    sa.ForeignKeyConstraint(['spot_id'], ['ad_spot.id'], name=op.f('fk_ad_contract_spot_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_ad_contract_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ad_contract'))
    )
    op.create_index('ix_ad_contract_tenant_end', 'ad_contract', ['tenant_id', 'end_date'], unique=False)
    op.create_index(op.f('ix_ad_contract_tenant_id'), 'ad_contract', ['tenant_id'], unique=False)
    op.create_index('ix_ad_contract_tenant_spot', 'ad_contract', ['tenant_id', 'spot_id'], unique=False)
    op.create_index('ix_ad_contract_tenant_status', 'ad_contract', ['tenant_id', 'status'], unique=False)
    # ### end Alembic commands ###

    protect(TABLES)


def downgrade() -> None:
    unprotect(TABLES)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ad_contract_tenant_status', table_name='ad_contract')
    op.drop_index('ix_ad_contract_tenant_spot', table_name='ad_contract')
    op.drop_index(op.f('ix_ad_contract_tenant_id'), table_name='ad_contract')
    op.drop_index('ix_ad_contract_tenant_end', table_name='ad_contract')
    op.drop_table('ad_contract')
    op.drop_index('uq_ad_spot_tenant_code', table_name='ad_spot')
    op.drop_index('ix_ad_spot_tenant_zone', table_name='ad_spot')
    op.drop_index(op.f('ix_ad_spot_tenant_id'), table_name='ad_spot')
    op.drop_table('ad_spot')
    # ### end Alembic commands ###
