"""equipment pos publishing

Revision ID: b43913998fa3
Revises: e338d7927d0e
Create Date: 2026-08-03 14:37:53.324716
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b43913998fa3'
down_revision: Union[str, None] = 'e338d7927d0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('sport_id', sa.UUID(), nullable=True))
    # server_default so existing rows backfill instead of failing the NOT NULL add —
    # published_to_pos defaults closed (nothing appears in POS until someone opts
    # it in), consumable defaults open (matches how most existing kit behaves today).
    op.add_column(
        'equipment',
        sa.Column('published_to_pos', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    )
    op.add_column('equipment', sa.Column('image_url', sa.Text(), nullable=True))
    op.add_column(
        'equipment',
        sa.Column('consumable', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    )
    op.create_index('ix_equipment_tenant_sport', 'equipment', ['tenant_id', 'sport_id'], unique=False)
    op.create_foreign_key(op.f('fk_equipment_sport_id'), 'equipment', 'sport', ['sport_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_equipment_sport_id'), 'equipment', type_='foreignkey')
    op.drop_index('ix_equipment_tenant_sport', table_name='equipment')
    op.drop_column('equipment', 'consumable')
    op.drop_column('equipment', 'image_url')
    op.drop_column('equipment', 'published_to_pos')
    op.drop_column('equipment', 'sport_id')
    # ### end Alembic commands ###
