"""admin: notifications, channel config, metering, jobs

Revision ID: e338d7927d0e
Revises: 4cd4baa51635
Create Date: 2026-08-02 01:50:09.993173
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic_rls import protect, unprotect

revision: str = 'e338d7927d0e'
down_revision: Union[str, None] = '4cd4baa51635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

TABLES = ("notification", "notification_channel_config", "notification_delivery", "job")

# NOTE: notification_delivery is deliberately NOT append-only, unlike audit_log and
# equipment_movement. A delivery row has a real lifecycle — queued -> sent ->
# delivered/failed, driven by provider webhooks arriving minutes later — so the
# application must be able to update it. Its integrity comes from `cost` being
# written once at send time, not from the row being immutable.


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('state', sa.Enum('pending', 'running', 'done', 'failed', name='job_state', native_enum=False, length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=64), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempts >= 0 AND max_attempts > 0', name=op.f('ck_job_attempts_sane')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_job_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job'))
    )
    op.create_index('ix_job_tenant_due', 'job', ['tenant_id', 'run_at'], unique=False, postgresql_where=sa.text("state = 'pending'"))
    op.create_index(op.f('ix_job_tenant_id'), 'job', ['tenant_id'], unique=False)
    op.create_table('notification',
    sa.Column('kind', sa.Enum('booking', 'payment', 'alert', 'equipment', 'membership', 'academy', 'advertising', name='notification_kind', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('severity_color', sa.String(length=9), nullable=True),
    sa.Column('target_user_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_notification_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    op.create_index('ix_notification_tenant_created', 'notification', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notification_tenant_id'), 'notification', ['tenant_id'], unique=False)
    op.create_index('ix_notification_tenant_unread', 'notification', ['tenant_id', 'created_at'], unique=False, postgresql_where=sa.text('read_at IS NULL'))
    op.create_table('notification_channel_config',
    sa.Column('event_key', sa.String(length=64), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('whatsapp_enabled', sa.Boolean(), nullable=False),
    sa.Column('sms_enabled', sa.Boolean(), nullable=False),
    sa.Column('lead_time_minutes', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_notification_channel_config_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_channel_config'))
    )
    op.create_index(op.f('ix_notification_channel_config_tenant_id'), 'notification_channel_config', ['tenant_id'], unique=False)
    op.create_index('uq_notification_channel_tenant_event', 'notification_channel_config', ['tenant_id', 'event_key'], unique=True)
    op.create_table('notification_delivery',
    sa.Column('event_key', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.Enum('email', 'whatsapp', 'sms', name='notification_channel', native_enum=False, length=32), nullable=False),
    sa.Column('recipient', sa.String(length=320), nullable=False),
    sa.Column('state', sa.Enum('queued', 'sent', 'delivered', 'failed', name='notification_delivery_state', native_enum=False, length=32), nullable=False),
    sa.Column('provider_message_id', sa.String(length=128), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cost >= 0', name=op.f('ck_notification_delivery_cost_non_negative')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_notification_delivery_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_delivery'))
    )
    op.create_index('ix_notification_delivery_tenant_channel', 'notification_delivery', ['tenant_id', 'channel', 'created_at'], unique=False)
    op.create_index(op.f('ix_notification_delivery_tenant_id'), 'notification_delivery', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    protect(TABLES)


def downgrade() -> None:
    unprotect(TABLES)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_delivery_tenant_id'), table_name='notification_delivery')
    op.drop_index('ix_notification_delivery_tenant_channel', table_name='notification_delivery')
    op.drop_table('notification_delivery')
    op.drop_index('uq_notification_channel_tenant_event', table_name='notification_channel_config')
    op.drop_index(op.f('ix_notification_channel_config_tenant_id'), table_name='notification_channel_config')
    op.drop_table('notification_channel_config')
    op.drop_index('ix_notification_tenant_unread', table_name='notification', postgresql_where=sa.text('read_at IS NULL'))
    op.drop_index(op.f('ix_notification_tenant_id'), table_name='notification')
    op.drop_index('ix_notification_tenant_created', table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_job_tenant_id'), table_name='job')
    op.drop_index('ix_job_tenant_due', table_name='job', postgresql_where=sa.text("state = 'pending'"))
    op.drop_table('job')
    # ### end Alembic commands ###
