"""booking domain

Revision ID: ed815e231c5c
Revises: 0a3362c950d9
Create Date: 2026-08-01 20:52:14.250297
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic_rls import protect, unprotect

revision: str = 'ed815e231c5c'

# Order matters for the FK graph on downgrade, not for RLS.
TABLES = (
    "sport",
    "court",
    "equipment",
    "equipment_movement",
    "customer",
    "booking",
    "booking_event",
)

# Inventory is a ledger: corrections are new ADJUST rows, never edits to history.
# Enforced by withholding the grant, the same way audit_log is.
APPEND_ONLY = ("equipment_movement",)
down_revision: Union[str, None] = '0a3362c950d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.Column('rental_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deposit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('condition', sa.Enum('excellent', 'good', 'fair', 'poor', name='equipment_condition', native_enum=False, length=32), nullable=False),
    sa.Column('qty_stock', sa.Integer(), nullable=False),
    sa.Column('qty_available', sa.Integer(), nullable=False),
    sa.Column('qty_issued', sa.Integer(), nullable=False),
    sa.Column('qty_maintenance', sa.Integer(), nullable=False),
    sa.Column('qty_lost', sa.Integer(), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('qty_available + qty_issued + qty_maintenance + qty_lost = qty_stock', name=op.f('ck_equipment_quantities_balance')),
    sa.CheckConstraint('qty_available >= 0 AND qty_issued >= 0 AND qty_maintenance >= 0 AND qty_lost >= 0', name=op.f('ck_equipment_quantities_non_negative')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_equipment_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment'))
    )
    op.create_index('ix_equipment_tenant_category', 'equipment', ['tenant_id', 'category'], unique=False)
    op.create_index(op.f('ix_equipment_tenant_id'), 'equipment', ['tenant_id'], unique=False)
    op.create_index('uq_equipment_tenant_barcode', 'equipment', ['tenant_id', 'barcode'], unique=True)
    op.create_table('sport',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=True),
    sa.Column('color', sa.String(length=9), nullable=True),
    sa.Column('bg_color', sa.String(length=9), nullable=True),
    sa.Column('default_duration_min', sa.Integer(), nullable=False),
    sa.Column('price_base', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_peak', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_weekend', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_sport_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sport'))
    )
    op.create_index(op.f('ix_sport_tenant_id'), 'sport', ['tenant_id'], unique=False)
    op.create_index('uq_sport_tenant_name', 'sport', ['tenant_id', 'name'], unique=True)
    op.create_index('uq_sport_tenant_slug', 'sport', ['tenant_id', 'slug'], unique=True)
    op.create_table('court',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('sport_id', sa.UUID(), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('peak_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('operating_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('amenities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_bookable', sa.Boolean(), nullable=False),
    sa.Column('maintenance_note', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sport.id'], name=op.f('fk_court_sport_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_court_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_court'))
    )
    op.create_index(op.f('ix_court_tenant_id'), 'court', ['tenant_id'], unique=False)
    op.create_index('ix_court_tenant_sport', 'court', ['tenant_id', 'sport_id'], unique=False)
    op.create_index('uq_court_tenant_code', 'court', ['tenant_id', 'code'], unique=True)
    op.create_table('customer',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='customer_gender', native_enum=False, length=32), nullable=True),
    sa.Column('member_type', sa.Enum('member', 'non-member', name='customer_member_type', native_enum=False, length=32), nullable=False),
    sa.Column('membership_tier', sa.Enum('gold', 'silver', 'bronze', name='customer_membership_tier', native_enum=False, length=32), nullable=True),
    sa.Column('join_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('favorite_sport_id', sa.UUID(), nullable=True),
    sa.Column('avatar_initials', sa.String(length=4), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('emergency_contact', sa.String(length=200), nullable=True),
    sa.Column('emergency_phone', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['favorite_sport_id'], ['sport.id'], name=op.f('fk_customer_favorite_sport_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_customer_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer'))
    )
    op.create_index(op.f('ix_customer_tenant_id'), 'customer', ['tenant_id'], unique=False)
    op.create_index('ix_customer_tenant_name', 'customer', ['tenant_id', 'name'], unique=False)
    op.create_index('uq_customer_tenant_email', 'customer', ['tenant_id', sa.literal_column('lower(email)')], unique=True, postgresql_where=sa.text('email IS NOT NULL'))
    op.create_index('uq_customer_tenant_phone', 'customer', ['tenant_id', 'phone'], unique=True)
    op.create_table('booking',
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('customer_phone', sa.String(length=32), nullable=True),
    sa.Column('sport_id', sa.UUID(), nullable=False),
    sa.Column('court_id', sa.UUID(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('time_range', postgresql.TSTZRANGE(), sa.Computed("tstzrange(starts_at, ends_at, '[)')", persisted=True), nullable=False),
    sa.Column('status', sa.Enum('upcoming', 'active', 'completed', 'overdue', 'cancelled', name='booking_status', native_enum=False, length=32), nullable=False),
    sa.Column('payment_status', sa.Enum('paid', 'pending', 'partial', 'refunded', name='booking_payment_status', native_enum=False, length=32), nullable=False),
    sa.Column('booking_type', sa.Enum('walkin', 'online', name='booking_type', native_enum=False, length=32), nullable=False),
    sa.Column('court_charge', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('equipment_charge', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('taxes', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=32), nullable=True),
    sa.Column('equipment', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    postgresql.ExcludeConstraint((sa.column('tenant_id'), '='), (sa.column('court_id'), '='), (sa.column('time_range'), '&&'), where=sa.text("status <> 'cancelled'"), using='gist', name='booking_no_overlap'),
    sa.CheckConstraint('amount_paid >= 0 AND total >= 0', name=op.f('ck_booking_amounts_non_negative')),
    sa.CheckConstraint('ends_at > starts_at', name=op.f('ck_booking_ends_after_starts')),
    sa.ForeignKeyConstraint(['court_id'], ['court.id'], name=op.f('fk_booking_court_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_booking_customer_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sport_id'], ['sport.id'], name=op.f('fk_booking_sport_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_booking_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking'))
    )
    op.create_index('ix_booking_tenant_court_start', 'booking', ['tenant_id', 'court_id', 'starts_at'], unique=False)
    op.create_index('ix_booking_tenant_customer', 'booking', ['tenant_id', 'customer_id'], unique=False)
    op.create_index(op.f('ix_booking_tenant_id'), 'booking', ['tenant_id'], unique=False)
    op.create_index('ix_booking_tenant_start', 'booking', ['tenant_id', 'starts_at'], unique=False)
    op.create_index('ix_booking_tenant_status', 'booking', ['tenant_id', 'status'], unique=False)
    op.create_table('booking_event',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('created', 'extended', 'equipment', 'payment', 'invoice', 'edit', 'note', 'cancelled', name='booking_event_kind', native_enum=False, length=32), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], name=op.f('fk_booking_event_booking_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_booking_event_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking_event'))
    )
    op.create_index('ix_booking_event_tenant_booking', 'booking_event', ['tenant_id', 'booking_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_booking_event_tenant_id'), 'booking_event', ['tenant_id'], unique=False)
    op.create_table('equipment_movement',
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('issue', 'return', 'to_maintenance', 'from_maintenance', 'lost', 'restock', 'adjust', name='equipment_movement_kind', native_enum=False, length=32), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('qty > 0', name=op.f('ck_equipment_movement_qty_positive')),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], name=op.f('fk_equipment_movement_booking_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_equipment_movement_equipment_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_equipment_movement_tenant_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment_movement'))
    )
    op.create_index('ix_equipment_movement_tenant_booking', 'equipment_movement', ['tenant_id', 'booking_id'], unique=False)
    op.create_index('ix_equipment_movement_tenant_equipment', 'equipment_movement', ['tenant_id', 'equipment_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_equipment_movement_tenant_id'), 'equipment_movement', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    protect(TABLES, append_only=APPEND_ONLY)


def downgrade() -> None:
    unprotect(TABLES)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_equipment_movement_tenant_id'), table_name='equipment_movement')
    op.drop_index('ix_equipment_movement_tenant_equipment', table_name='equipment_movement')
    op.drop_index('ix_equipment_movement_tenant_booking', table_name='equipment_movement')
    op.drop_table('equipment_movement')
    op.drop_index(op.f('ix_booking_event_tenant_id'), table_name='booking_event')
    op.drop_index('ix_booking_event_tenant_booking', table_name='booking_event')
    op.drop_table('booking_event')
    op.drop_index('ix_booking_tenant_status', table_name='booking')
    op.drop_index('ix_booking_tenant_start', table_name='booking')
    op.drop_index(op.f('ix_booking_tenant_id'), table_name='booking')
    op.drop_index('ix_booking_tenant_customer', table_name='booking')
    op.drop_index('ix_booking_tenant_court_start', table_name='booking')
    op.drop_table('booking')
    op.drop_index('uq_customer_tenant_phone', table_name='customer')
    op.drop_index('uq_customer_tenant_email', table_name='customer', postgresql_where=sa.text('email IS NOT NULL'))
    op.drop_index('ix_customer_tenant_name', table_name='customer')
    op.drop_index(op.f('ix_customer_tenant_id'), table_name='customer')
    op.drop_table('customer')
    op.drop_index('uq_court_tenant_code', table_name='court')
    op.drop_index('ix_court_tenant_sport', table_name='court')
    op.drop_index(op.f('ix_court_tenant_id'), table_name='court')
    op.drop_table('court')
    op.drop_index('uq_sport_tenant_slug', table_name='sport')
    op.drop_index('uq_sport_tenant_name', table_name='sport')
    op.drop_index(op.f('ix_sport_tenant_id'), table_name='sport')
    op.drop_table('sport')
    op.drop_index('uq_equipment_tenant_barcode', table_name='equipment')
    op.drop_index(op.f('ix_equipment_tenant_id'), table_name='equipment')
    op.drop_index('ix_equipment_tenant_category', table_name='equipment')
    op.drop_table('equipment')
    # ### end Alembic commands ###
